nginx_configs:
  proxy:
    - proxy_set_header X-Real-IP $remote_addr
    - proxy_set_header Host $http_host
    - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
    - proxy_set_header X-NginX-Proxy true
    - proxy_redirect off
    - proxy_http_version 1.1
    - proxy_set_header Upgrade $http_upgrade
    - proxy_set_header Connection "upgrade"

nginx_sites:
  easyCircos:
    - listen 80
    - server_name easyCircos
    - error_log /var/log/nginx/easyCircos.error.log
    - access_log /var/log/nginx/easyCircos.access.log
    - location / {
            proxy_pass http://127.0.0.1:3000/;
      }