---
# file: playbook.yml

- name: Deploy
  hosts: all
  vars_files:
    - vars/f500.yml
  roles:
    - { role: vendors/roles/f500.project_deploy, tags: 'f500' }
  post_tasks:
    - name: Build easy Circos
      command: /var/www/easyCircos/current/node_modules/gulp/bin/gulp build

    - name: Start server
      command: supervisorctl restart easyCircosServer
