---
# file: playbook.yml

- name: Deploy
  hosts: all
  vars_files:
    - vars/project_deploy.yml
  roles:
    - { role: vendors/roles/f500.project_deploy, tags: 'f500' }
  post_tasks:
    - name: Build easy Circos
      command: node_modules/gulp/bin/gulp.js build
      args:
        chdir: /var/www/easyCircos/current
    - name: Start server
      command: supervisorctl restart easyCircosServer
