---
# file: playbook.yml

- name: Deploy
  hosts: all
  vars_files:
    - vars/f500.yml
  roles:
    - { role: vendors/roles/f500.project_deploy, tags: 'f500' }
  post_tasks:
    - name: Install node modules
      npm:
        path=/var/www/easyCircos
        state=present
    - name: Install bower modules
      shell: bower install
      args:
        - chdir: /var/www/easyCircos
    - name: Build Easy Circos App
      shell: gulp build
      args:
        - chdir: /var/www/easyCircos
    - name: Start server
      command: supervisorctl restart easyCircosServer
